var that=this;function __skpm_run(e,t){that.context=t;var r=function(e){var t={};function r(n){if(t[n])return t[n].exports;var a=t[n]={i:n,l:!1,exports:{}};return e[n].call(a.exports,a,a.exports,r),a.l=!0,a.exports}return r.m=e,r.c=t,r.d=function(e,t,n){r.o(e,t)||Object.defineProperty(e,t,{enumerable:!0,get:n})},r.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r.t=function(e,t){if(1&t&&(e=r(e)),8&t)return e;if(4&t&&"object"==typeof e&&e&&e.__esModule)return e;var n=Object.create(null);if(r.r(n),Object.defineProperty(n,"default",{enumerable:!0,value:e}),2&t&&"string"!=typeof e)for(var a in e)r.d(n,a,function(t){return e[t]}.bind(null,a));return n},r.n=function(e){var t=e&&e.__esModule?function(){return e.default}:function(){return e};return r.d(t,"a",t),t},r.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},r.p="",r(r.s="./src/index.js")}({"./src/index.js":
/*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/
/*! no static exports found */function(e,t,r){var n=r(/*! sketch */"sketch"),a=r(/*! ./util */"./src/util.js"),u={adjustSelected:function(){var e=n.getSelectedDocument().selectedLayers,t=u.adjustLayers(e,!1);n.UI.message(u.resultsString(t))},adjustNested:function(){var e=n.getSelectedDocument().selectedLayers,t=u.adjustLayers(e,!0);n.UI.message(u.resultsString(t))},adjustLayers:function(e,t){var r={};return e.forEach(function(e){var n={};if(t&&e.layers){var a=u.adjustLayers(e.layers,t);for(var s in a)a.hasOwnProperty(s)&&(n=a);delete n.failed}var c=e.sketchObject.frame().height(),o=u.adjustToFit(e),i=e.sketchObject.frame().height(),d="failed";for(var f in o&&(d=i!==c?e.type.toLowerCase():"unaffected"),n[d]=n[d]+1||1,n)n.hasOwnProperty(f)&&(r[f]=r[f]+n[f]||n[f])}),r},adjustToFit:function(e){return("Group"===e.type||"Text"===e.type||"Artboard"===e.type)&&("Group"===e.type||"Artboard"===e.type?e.adjustToFit():u.adjustTextToFit(e),!0)},adjustTextToFit:function(e){var t=e.sketchObject.frame().y()+e.fragments[0].rect.y;e.sketchObject.frame().y=t;e.sketchObject.frame().height();var r=e.fragments.reduce(function(e,t){return e+t.rect.height},0);e.sketchObject.frame().height=r},resultsString:function(e){var t=e.failed;delete e.failed;var r=e.unaffected;delete e.unaffected;var n=[];for(var u in e)if(e.hasOwnProperty(u)){var s=e[u];"text"===u&&(u="text layer"),n.push(a.pluralize(s,u))}var c=[];return n.length>0&&c.push("".concat(a.commify(n)," adjusted successfully")),r>0&&c.push("".concat(a.pluralize(r,"layer")," unaffected")),t>0&&c.push("".concat(t," failed")),c.join(", ")}};e.exports.adjustSelected=u.adjustSelected,e.exports.adjustNested=u.adjustNested},"./src/util.js":
/*!*********************!*\
  !*** ./src/util.js ***!
  \*********************/
/*! no static exports found */function(e,t){var r=e.exports={};r.pluralize=function(e,t){return e>1&&(t+="s"),"".concat(e," ").concat(t)},r.commify=function(e){switch(e.length){case 0:return;case 1:return e[0];case 2:return"".concat(e[0]," and ").concat(e[1]);default:var t=e.pop();return e.join(", ")+" and ".concat(t)}}},sketch:
/*!*************************!*\
  !*** external "sketch" ***!
  \*************************/
/*! no static exports found */function(e,t){e.exports=require("sketch")}});"default"===e&&"function"==typeof r?r(t):r[e](t)}that.adjustSelected=__skpm_run.bind(this,"adjustSelected"),that.onRun=__skpm_run.bind(this,"default"),that.adjustNested=__skpm_run.bind(this,"adjustNested");